
INSERT INTO SALES (CUSTOMER_ID, PRODUCT_ID, SALE_DATE, QUANTITY, UNIT_PRICE, REGION) 
SELECT CUSTOMER_ID, PRODUCT_ID, SALE_DATE, QUANTITY, UNIT_PRICE, REGION FROM SALES;

COMMIT;


SELECT COUNT(*) FROM SALES;
