ALTER TABLE FACT_EOD_RISK ADD CONSTRAINT fk_trade_id
    FOREIGN KEY (TRADE_ID) REFERENCES DIM_TRADE (TRADE_ID);

ALTER TABLE FACT_EOD_RISK ADD CONSTRAINT fk_instrument_id
    FOREIGN KEY (INSTRUMENT_ID) REFERENCES DIM_INSTRUMENT (INSTRUMENT_ID);

ALTER TABLE FACT_EOD_RISK ADD CONSTRAINT fk_issuer_id
    FOREIGN KEY (ISSUER_ID) REFERENCES DIM_ISSUER (ISSUER_ID);

ALTER TABLE FACT_EOD_RISK ADD CONSTRAINT fk_risk_factor_code
    FOREIGN KEY (RISK_FACTOR_CODE) REFERENCES DIM_RISK_FACTOR (RISK_FACTOR_CODE);

ALTER TABLE FACT_EOD_RISK ADD CONSTRAINT fk_rpl_book_id
    FOREIGN KEY (RPL_BOOK_ID) REFERENCES DIM_BOOK (RPL_BOOK_ID);

ALTER TABLE FACT_EOD_RISK ADD CONSTRAINT fk_rpl_location_id
    FOREIGN KEY (RPL_LOCATION_ID) REFERENCES DIM_LOCATION (RPL_LOCATION_ID);

ALTER TABLE FACT_EOD_RISK ADD CONSTRAINT fk_rpl_subsidiary_id
    FOREIGN KEY (RPL_SUBSIDIARY_ID) REFERENCES DIM_SUBSIDIARY (RPL_SUBSIDIARY_ID);

ALTER TABLE FACT_EOD_RISK ADD CONSTRAINT fk_rpl_unit_id
    FOREIGN KEY (RPL_UNIT_ID) REFERENCES DIM_UNIT (RPL_UNIT_ID);

ALTER TABLE FACT_EOD_RISK ADD CONSTRAINT fk_pkg_id
    FOREIGN KEY (PKG_ID) REFERENCES DIM_PACKAGE (PKG_ID);

ALTER TABLE FACT_EOD_RISK ADD CONSTRAINT fk_cob_date
    FOREIGN KEY (COB_DATE) REFERENCES DIM_TIME (COB_DATE);
